# Server setup
timezone: Europe/Berlin
url: "https://adrsrv.duckdns.org"
baseurl: ""

# Blog
title: "Zeno's Homepage"
tagline: "My Homepage"
description: "A webpage and blog for me, Zeno, a 17 year old dude interested in Linux, FOSS, selfhosting and other stuff."

# Author/Contact
author:
  name: Zeno
  url: "https://adrsrv.duckdns.org"
  email: "adrsrv@protonmail.org"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-org
